name: Build Extension (CS3)

on:
  workflow_dispatch:
    inputs:
      extension:
        description: "Nombre del módulo (ej: gnulahd, cuevana, etc)"
        required: true
        default: "gnulahd"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Permisos gradle
        run: chmod +x ./gradlew

      # 🔥 DEBUG (para ver qué mandaste)
      - name: Mostrar extensión
        run: echo "Building extension: ${{ github.event.inputs.extension }}"

      # 🚀 BUILD DINÁMICO
      - name: Build CS3
        run: ./gradlew :${{ github.event.inputs.extension }}:make

      # 📦 SUBIR RESULTADO
      - name: Upload CS3
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.extension }}-cs3
          path: "**/*.cs3"
